[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "01-trebuchet"
path = "src/01-trebuchet.rs"

[[bin]]
name = "02-cubes"
path = "src/02-cubes.rs"

[dependencies]
regex = "1.10.2"
